name: Run tests

on:
  push:
    branches: main

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull docker image
        run: |
          docker pull mluczynski/cbind:latest

      - name: Run tests
        run: |
          docker run --rm mluczynski/cbind:latest /bin/bash -c "cd tests && ./validate.sh"

      
