name: Run tests

on:
  push:
    branches: main

jobs: 
  test:
    runs-on: archlinux-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up build tools/dependencies for Lua and C
        run: |
          sudo pacman -Syu --no-confirm 
          sudo pacman -S --no-confirm base-devel gcc ffcall

      - name: Download and build Lua
        run: |
          curl -L -R -O https://www.lua.org/ftp/lua-5.4.7.tar.gz
          tar zxf lua-5.4.7.tar.gz
          cd lua-5.4.7
          sudo make linux install

      - name: Check Lua and gcc installation
        run: |
          lua -v
          ls /usr/local/lib | grep liblua
          gcc --version

      - name: Build and run tests
        run: |
          cd tests
          bash validate.sh

      
